### ISSUE TITLE
Add a license for source code

### ISSUE THREAD

**Issue by wieslawsoltes** [cuikp/AvRichTextBox#3]
The LICENSE is missing so using the code is impossible.

**Comment by cuikp** [comment]
Sorry about that, I'll figure out how to add a License ...

**Comment by wieslawsoltes** [comment]
> Sorry about that, I'll figure out how to add a License ...

Simplest is to use GitHub and add new file, type LICENSE into file name and selected template :)

**Comment by wieslawsoltes** [comment]
@cuikp I think you have typo in first line https://github.com/cuikp/AvRichTextBox/blob/1775860905ab83ce2ad88b29f5a05de5f81ac47d/LICENSE.txt#L1

should it be MIT ?

**Comment by cuikp** [comment]
Indeed it should :)  Thanks for the heads-up

**Comment by wieslawsoltes** [comment]
@cuikp thanks for addin https://github.com/cuikp/AvRichTextBox/blob/main/LICENSE.txt, closing as its solved
